name: build/pub release
on:
  push:
    branches: main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd node && npm ci
      - name: Run audit test
        run: cd node && npm run test:audit
      - name: Run format test
        run: cd node && npm run test:format
      - name: Run lint test
        run: cd node && npm run test:lint
      - name: Run types test
        run: cd node && npm run test:types
      - name: Run license test
        run: cd node && npm run test:license
      - name: Run tests
        run: cd node && npm run test

  build-and-publish:
    needs: test
    name: Push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker tag
        id: tag
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          echo ::set-output name=image_tag::${IMAGE_TAG}
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker build
        run: DOCKER_IMAGE=uscictdocker/opentutor-dialog:${{ steps.tag.outputs.image_tag }} make docker-build
      - name: Docker tag
        if: startsWith(github.ref, 'refs/tags/')
        run: docker tag "uscictdocker/opentutor-dialog:${{ steps.tag.outputs.image_tag }}" "uscictdocker/opentutor-dialog:${GITHUB_REF#refs/tags/}"
      - name: Docker push
        run: docker push uscictdocker/opentutor-dialog
