name: Test
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: cd node && npm ci
      - name: Run audit test
        run: cd node && npm run test:audit
      - name: Run format test
        run: cd node && npm run test:format
      - name: Run lint test
        run: cd node && npm run test:lint
      - name: Run types test
        run: cd node && npm run test:types
      - name: Run license test
        run: cd node && npm run test:license
      - name: Run tests
        run: cd node && npm run test

  